## csvファイルを作成するためのコード（不必要）

import csv
 
with open('weather_data.csv', 'w') as csv_file:
    fieldnames = ['weather_id', 'text']
    writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerow({ 'weather_id' : 200 , 'text' : '小雨による雷雨'})
    writer.writerow({ 'weather_id' : 201 , 'text' : '雨による雷雨'})
    writer.writerow({ 'weather_id' : 202 , 'text' : '豪雨による雷雨'})
    writer.writerow({ 'weather_id' : 210 , 'text' : '小さい雷雨'})
    writer.writerow({ 'weather_id' : 211 , 'text' : '雷雨'})
    writer.writerow({ 'weather_id' : 212 , 'text' : '激しい雷雨'})
    writer.writerow({ 'weather_id' : 221 , 'text' : 'ぼろぼろの雷雨'})
    writer.writerow({ 'weather_id' : 230 , 'text' : '小さい霧雨による雷雨'})
    writer.writerow({ 'weather_id' : 231 , 'text' : '霧雨による雷雨'})
    writer.writerow({ 'weather_id' : 232 , 'text' : 'ひどい霧雨による雷雨'})
    writer.writerow({ 'weather_id' : 300 , 'text' : '光度霧雨'})
    writer.writerow({ 'weather_id' : 301 , 'text' : '霧雨'})
    writer.writerow({ 'weather_id' : 302 , 'text' : 'ひどい強さ霧雨'})
    writer.writerow({ 'weather_id' : 310 , 'text' : '光度霧雨雨'})
    writer.writerow({ 'weather_id' : 311 , 'text' : '霧雨雨'})
    writer.writerow({ 'weather_id' : 312 , 'text' : 'ひどい強さ霧雨雨'})
    writer.writerow({ 'weather_id' : 313 , 'text' : 'シャワー雨と霧雨'})
    writer.writerow({ 'weather_id' : 314 , 'text' : 'ひどいシャワー雨と霧雨'})
    writer.writerow({ 'weather_id' : 321 , 'text' : 'シャワー霧雨'})
    writer.writerow({ 'weather_id' : 500 , 'text' : '小雨'})
    writer.writerow({ 'weather_id' : 501 , 'text' : '穏やかな雨'})
    writer.writerow({ 'weather_id' : 502 , 'text' : 'ひどい強さ雨'})
    writer.writerow({ 'weather_id' : 503 , 'text' : '非常にひどい雨'})
    writer.writerow({ 'weather_id' : 504 , 'text' : '最大の雨'})
    writer.writerow({ 'weather_id' : 511 , 'text' : '凍るような雨'})
    writer.writerow({ 'weather_id' : 520 , 'text' : '光度シャワー雨'})
    writer.writerow({ 'weather_id' : 521 , 'text' : 'シャワー雨'})
    writer.writerow({ 'weather_id' : 522 , 'text' : 'ひどい強さシャワー雨'})
    writer.writerow({ 'weather_id' : 531 , 'text' : 'ぼろぼろのシャワー雨'})
    writer.writerow({ 'weather_id' : 600 , 'text' : '小雪'})
    writer.writerow({ 'weather_id' : 601 , 'text' : '雪'})
    writer.writerow({ 'weather_id' : 602 , 'text' : '大雪'})
    writer.writerow({ 'weather_id' : 611 , 'text' : 'みぞれ'})
    writer.writerow({ 'weather_id' : 612 , 'text' : 'シャワーみぞれ'})
    writer.writerow({ 'weather_id' : 615 , 'text' : '小雨と雪'})
    writer.writerow({ 'weather_id' : 616 , 'text' : '雨と雪'})
    writer.writerow({ 'weather_id' : 620 , 'text' : '小さいシャワー雪'})
    writer.writerow({ 'weather_id' : 621 , 'text' : 'シャワー雪'})
    writer.writerow({ 'weather_id' : 622 , 'text' : 'ひどいシャワー雪'})
    writer.writerow({ 'weather_id' : 701 , 'text' : '霧'})
    writer.writerow({ 'weather_id' : 711 , 'text' : '煙'})
    writer.writerow({ 'weather_id' : 721 , 'text' : 'もや'})
    writer.writerow({ 'weather_id' : 731 , 'text' : '砂、塵旋風'})
    writer.writerow({ 'weather_id' : 741 , 'text' : '霧'})
    writer.writerow({ 'weather_id' : 751 , 'text' : '砂'})
    writer.writerow({ 'weather_id' : 761 , 'text' : 'ちり'})
    writer.writerow({ 'weather_id' : 762 , 'text' : '火山灰'})
    writer.writerow({ 'weather_id' : 771 , 'text' : 'スコール'})
    writer.writerow({ 'weather_id' : 781 , 'text' : '竜巻'})
    writer.writerow({ 'weather_id' : 800 , 'text' : '晴天'})
    writer.writerow({ 'weather_id' : 801 , 'text' : '晴れ'})
    writer.writerow({ 'weather_id' : 802 , 'text' : '千切れ雲'})
    writer.writerow({ 'weather_id' : 803 , 'text' : '千切れ雲'})
    writer.writerow({ 'weather_id' : 804 , 'text' : 'くもり'})
    writer.writerow({ 'weather_id' : 900 , 'text' : '竜巻'})
    writer.writerow({ 'weather_id' : 901 , 'text' : '熱帯低気圧'})
    writer.writerow({ 'weather_id' : 902 , 'text' : 'ハリケーン'})
    writer.writerow({ 'weather_id' : 903 , 'text' : '寒冷'})
    writer.writerow({ 'weather_id' : 904 , 'text' : '高温'})
    writer.writerow({ 'weather_id' : 905 , 'text' : '風が強い'})
    writer.writerow({ 'weather_id' : 906 , 'text' : 'ひょう'})
    writer.writerow({ 'weather_id' : 951 , 'text' : '落ちつき'})
    writer.writerow({ 'weather_id' : 952 , 'text' : '軽風'})
    writer.writerow({ 'weather_id' : 953 , 'text' : '軟風'})
    writer.writerow({ 'weather_id' : 954 , 'text' : '和風'})
    writer.writerow({ 'weather_id' : 955 , 'text' : '疾風'})
    writer.writerow({ 'weather_id' : 956 , 'text' : '雄風'})
    writer.writerow({ 'weather_id' : 957 , 'text' : '強風、強風'})
    writer.writerow({ 'weather_id' : 958 , 'text' : '強風'})
    writer.writerow({ 'weather_id' : 959 , 'text' : '厳しい強風'})
    writer.writerow({ 'weather_id' : 960 , 'text' : '嵐'})
    writer.writerow({ 'weather_id' : 961 , 'text' : '暴風'})
    writer.writerow({ 'weather_id' :962 , 'text' : 'ハリケーン'})
 